#ifndef _VERSION_H_
#define _VERSION_H_

#define APPLICATION_NAME "@CMAKE_PROJECT_NAME@"
#define VERSION_MAJOR  @CMAKE_PROJECT_VERSION_MAJOR@
#define VERSION_MINOR  @CMAKE_PROJECT_VERSION_MINOR@
#define VERSION_PATCH  @CMAKE_PROJECT_VERSION_PATCH@
#define VERSION_TWEAK  @CMAKE_PROJECT_VERSION_TWEAK@

#endif